name: animation_debugger
description: A smart animation debugger with timeline for every animation controller in your app
homepage: https://github.com/alphamikle/animation_debugger
repository: https://github.com/alphamikle/animation_debugger
version: 1.0.0

environment:
  sdk: '>=2.18.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true